# Generated by Django 5.0.3 on 2025-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="language_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="language_probability",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="words_json",
            field=models.JSONField(null=True),
        ),
    ]
