# Generated by Django 5.2 on 2025-04-11 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0003_recordingsession_transcription_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingsession",
            name="latest_insight_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordingsession",
            name="latest_insight_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordingsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
