# Generated by Django 5.2 on 2025-04-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0004_recordingsession_latest_insight_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="generated_insight_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="language_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="language_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="words_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
