# Generated by Django 5.2 on 2025-04-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('recorder', '0006_alter_recordingsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recorder.campaign'),
        ),
    ]
