# Generated by Django 5.2 on 2025-04-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='openai_file_id',
            field=models.CharField(blank=True, help_text='OpenAI File ID', max_length=255, null=True, unique=True),
        ),
    ]
